/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type { Image, Audio, Pdf, Video } from "@boundaryml/baml"
import type { Checked, Check } from "./types"
import type {  AgentRole,  ReviewVerdict,  VerdictCode,  WorkflowEdge,  WorkflowPlan,  WorkflowStep } from "./types"
import type * as types from "./types"

/******************************************************************************
*
*  These types are used for streaming, for when an instance of a type
*  is still being built up and any of its fields is not yet fully available.
*
******************************************************************************/

export interface StreamState<T> {
  value: T
  state: "Pending" | "Incomplete" | "Complete"
}

export namespace partial_types {
    export interface ReviewVerdict {
      verdict?: types.VerdictCode | null
      score?: number | null
      rationale?: string | null
      blockers: string[]
    }
    export interface WorkflowEdge {
      from?: string | null
      to?: string | null
      when?: string | null
    }
    export interface WorkflowPlan {
      steps: WorkflowStep[]
      edges: WorkflowEdge[]
      entry?: string | null
    }
    export interface WorkflowStep {
      id?: string | null
      role?: types.AgentRole | null
      description?: string | null
      tools: string[]
      inputs: string[]
    }
}