# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from dkod.v1 import agent_pb2 as dkod_dot_v1_dot_agent__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in dkod/v1/agent_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AgentServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Connect = channel.unary_unary(
                '/dkod.v1.AgentService/Connect',
                request_serializer=dkod_dot_v1_dot_agent__pb2.ConnectRequest.SerializeToString,
                response_deserializer=dkod_dot_v1_dot_agent__pb2.ConnectResponse.FromString,
                _registered_method=True)
        self.Context = channel.unary_unary(
                '/dkod.v1.AgentService/Context',
                request_serializer=dkod_dot_v1_dot_agent__pb2.ContextRequest.SerializeToString,
                response_deserializer=dkod_dot_v1_dot_agent__pb2.ContextResponse.FromString,
                _registered_method=True)
        self.Submit = channel.unary_unary(
                '/dkod.v1.AgentService/Submit',
                request_serializer=dkod_dot_v1_dot_agent__pb2.SubmitRequest.SerializeToString,
                response_deserializer=dkod_dot_v1_dot_agent__pb2.SubmitResponse.FromString,
                _registered_method=True)
        self.Verify = channel.unary_stream(
                '/dkod.v1.AgentService/Verify',
                request_serializer=dkod_dot_v1_dot_agent__pb2.VerifyRequest.SerializeToString,
                response_deserializer=dkod_dot_v1_dot_agent__pb2.VerifyStepResult.FromString,
                _registered_method=True)
        self.Merge = channel.unary_unary(
                '/dkod.v1.AgentService/Merge',
                request_serializer=dkod_dot_v1_dot_agent__pb2.MergeRequest.SerializeToString,
                response_deserializer=dkod_dot_v1_dot_agent__pb2.MergeResponse.FromString,
                _registered_method=True)
        self.Watch = channel.unary_stream(
                '/dkod.v1.AgentService/Watch',
                request_serializer=dkod_dot_v1_dot_agent__pb2.WatchRequest.SerializeToString,
                response_deserializer=dkod_dot_v1_dot_agent__pb2.WatchEvent.FromString,
                _registered_method=True)
        self.FileRead = channel.unary_unary(
                '/dkod.v1.AgentService/FileRead',
                request_serializer=dkod_dot_v1_dot_agent__pb2.FileReadRequest.SerializeToString,
                response_deserializer=dkod_dot_v1_dot_agent__pb2.FileReadResponse.FromString,
                _registered_method=True)
        self.FileWrite = channel.unary_unary(
                '/dkod.v1.AgentService/FileWrite',
                request_serializer=dkod_dot_v1_dot_agent__pb2.FileWriteRequest.SerializeToString,
                response_deserializer=dkod_dot_v1_dot_agent__pb2.FileWriteResponse.FromString,
                _registered_method=True)
        self.FileList = channel.unary_unary(
                '/dkod.v1.AgentService/FileList',
                request_serializer=dkod_dot_v1_dot_agent__pb2.FileListRequest.SerializeToString,
                response_deserializer=dkod_dot_v1_dot_agent__pb2.FileListResponse.FromString,
                _registered_method=True)
        self.PreSubmitCheck = channel.unary_unary(
                '/dkod.v1.AgentService/PreSubmitCheck',
                request_serializer=dkod_dot_v1_dot_agent__pb2.PreSubmitCheckRequest.SerializeToString,
                response_deserializer=dkod_dot_v1_dot_agent__pb2.PreSubmitCheckResponse.FromString,
                _registered_method=True)
        self.GetSessionStatus = channel.unary_unary(
                '/dkod.v1.AgentService/GetSessionStatus',
                request_serializer=dkod_dot_v1_dot_agent__pb2.SessionStatusRequest.SerializeToString,
                response_deserializer=dkod_dot_v1_dot_agent__pb2.SessionStatusResponse.FromString,
                _registered_method=True)
        self.Push = channel.unary_unary(
                '/dkod.v1.AgentService/Push',
                request_serializer=dkod_dot_v1_dot_agent__pb2.PushRequest.SerializeToString,
                response_deserializer=dkod_dot_v1_dot_agent__pb2.PushResponse.FromString,
                _registered_method=True)
        self.Approve = channel.unary_unary(
                '/dkod.v1.AgentService/Approve',
                request_serializer=dkod_dot_v1_dot_agent__pb2.ApproveRequest.SerializeToString,
                response_deserializer=dkod_dot_v1_dot_agent__pb2.ApproveResponse.FromString,
                _registered_method=True)
        self.Resolve = channel.unary_unary(
                '/dkod.v1.AgentService/Resolve',
                request_serializer=dkod_dot_v1_dot_agent__pb2.ResolveRequest.SerializeToString,
                response_deserializer=dkod_dot_v1_dot_agent__pb2.ResolveResponse.FromString,
                _registered_method=True)
        self.Close = channel.unary_unary(
                '/dkod.v1.AgentService/Close',
                request_serializer=dkod_dot_v1_dot_agent__pb2.CloseRequest.SerializeToString,
                response_deserializer=dkod_dot_v1_dot_agent__pb2.CloseResponse.FromString,
                _registered_method=True)
        self.Review = channel.unary_unary(
                '/dkod.v1.AgentService/Review',
                request_serializer=dkod_dot_v1_dot_agent__pb2.ReviewRequest.SerializeToString,
                response_deserializer=dkod_dot_v1_dot_agent__pb2.ReviewResponse.FromString,
                _registered_method=True)
        self.RecordReview = channel.unary_unary(
                '/dkod.v1.AgentService/RecordReview',
                request_serializer=dkod_dot_v1_dot_agent__pb2.RecordReviewRequest.SerializeToString,
                response_deserializer=dkod_dot_v1_dot_agent__pb2.RecordReviewResponse.FromString,
                _registered_method=True)


class AgentServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Connect(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Context(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Submit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Verify(self, request, context):
        """Trigger verification pipeline on a changeset (server-streaming)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Merge(self, request, context):
        """Merge an approved changeset into a Git commit
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Watch(self, request, context):
        """Watch for repo events from other agents (server-streaming)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FileRead(self, request, context):
        """File-level operations through the session workspace overlay
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FileWrite(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FileList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PreSubmitCheck(self, request, context):
        """Dry-run conflict detection before SUBMIT
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSessionStatus(self, request, context):
        """Get current session workspace state
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Push(self, request, context):
        """Push merged changes to GitHub (branch or PR)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Approve(self, request, context):
        """Approve a submitted changeset (platform-level state transition)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Resolve(self, request, context):
        """Resolve conflicts on a changeset
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Close(self, request, context):
        """Close a session and destroy its workspace
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Review(self, request, context):
        """Get code review results for a changeset
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecordReview(self, request, context):
        """Record a completed code review result (called by the harness after deep review)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Connect': grpc.unary_unary_rpc_method_handler(
                    servicer.Connect,
                    request_deserializer=dkod_dot_v1_dot_agent__pb2.ConnectRequest.FromString,
                    response_serializer=dkod_dot_v1_dot_agent__pb2.ConnectResponse.SerializeToString,
            ),
            'Context': grpc.unary_unary_rpc_method_handler(
                    servicer.Context,
                    request_deserializer=dkod_dot_v1_dot_agent__pb2.ContextRequest.FromString,
                    response_serializer=dkod_dot_v1_dot_agent__pb2.ContextResponse.SerializeToString,
            ),
            'Submit': grpc.unary_unary_rpc_method_handler(
                    servicer.Submit,
                    request_deserializer=dkod_dot_v1_dot_agent__pb2.SubmitRequest.FromString,
                    response_serializer=dkod_dot_v1_dot_agent__pb2.SubmitResponse.SerializeToString,
            ),
            'Verify': grpc.unary_stream_rpc_method_handler(
                    servicer.Verify,
                    request_deserializer=dkod_dot_v1_dot_agent__pb2.VerifyRequest.FromString,
                    response_serializer=dkod_dot_v1_dot_agent__pb2.VerifyStepResult.SerializeToString,
            ),
            'Merge': grpc.unary_unary_rpc_method_handler(
                    servicer.Merge,
                    request_deserializer=dkod_dot_v1_dot_agent__pb2.MergeRequest.FromString,
                    response_serializer=dkod_dot_v1_dot_agent__pb2.MergeResponse.SerializeToString,
            ),
            'Watch': grpc.unary_stream_rpc_method_handler(
                    servicer.Watch,
                    request_deserializer=dkod_dot_v1_dot_agent__pb2.WatchRequest.FromString,
                    response_serializer=dkod_dot_v1_dot_agent__pb2.WatchEvent.SerializeToString,
            ),
            'FileRead': grpc.unary_unary_rpc_method_handler(
                    servicer.FileRead,
                    request_deserializer=dkod_dot_v1_dot_agent__pb2.FileReadRequest.FromString,
                    response_serializer=dkod_dot_v1_dot_agent__pb2.FileReadResponse.SerializeToString,
            ),
            'FileWrite': grpc.unary_unary_rpc_method_handler(
                    servicer.FileWrite,
                    request_deserializer=dkod_dot_v1_dot_agent__pb2.FileWriteRequest.FromString,
                    response_serializer=dkod_dot_v1_dot_agent__pb2.FileWriteResponse.SerializeToString,
            ),
            'FileList': grpc.unary_unary_rpc_method_handler(
                    servicer.FileList,
                    request_deserializer=dkod_dot_v1_dot_agent__pb2.FileListRequest.FromString,
                    response_serializer=dkod_dot_v1_dot_agent__pb2.FileListResponse.SerializeToString,
            ),
            'PreSubmitCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.PreSubmitCheck,
                    request_deserializer=dkod_dot_v1_dot_agent__pb2.PreSubmitCheckRequest.FromString,
                    response_serializer=dkod_dot_v1_dot_agent__pb2.PreSubmitCheckResponse.SerializeToString,
            ),
            'GetSessionStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSessionStatus,
                    request_deserializer=dkod_dot_v1_dot_agent__pb2.SessionStatusRequest.FromString,
                    response_serializer=dkod_dot_v1_dot_agent__pb2.SessionStatusResponse.SerializeToString,
            ),
            'Push': grpc.unary_unary_rpc_method_handler(
                    servicer.Push,
                    request_deserializer=dkod_dot_v1_dot_agent__pb2.PushRequest.FromString,
                    response_serializer=dkod_dot_v1_dot_agent__pb2.PushResponse.SerializeToString,
            ),
            'Approve': grpc.unary_unary_rpc_method_handler(
                    servicer.Approve,
                    request_deserializer=dkod_dot_v1_dot_agent__pb2.ApproveRequest.FromString,
                    response_serializer=dkod_dot_v1_dot_agent__pb2.ApproveResponse.SerializeToString,
            ),
            'Resolve': grpc.unary_unary_rpc_method_handler(
                    servicer.Resolve,
                    request_deserializer=dkod_dot_v1_dot_agent__pb2.ResolveRequest.FromString,
                    response_serializer=dkod_dot_v1_dot_agent__pb2.ResolveResponse.SerializeToString,
            ),
            'Close': grpc.unary_unary_rpc_method_handler(
                    servicer.Close,
                    request_deserializer=dkod_dot_v1_dot_agent__pb2.CloseRequest.FromString,
                    response_serializer=dkod_dot_v1_dot_agent__pb2.CloseResponse.SerializeToString,
            ),
            'Review': grpc.unary_unary_rpc_method_handler(
                    servicer.Review,
                    request_deserializer=dkod_dot_v1_dot_agent__pb2.ReviewRequest.FromString,
                    response_serializer=dkod_dot_v1_dot_agent__pb2.ReviewResponse.SerializeToString,
            ),
            'RecordReview': grpc.unary_unary_rpc_method_handler(
                    servicer.RecordReview,
                    request_deserializer=dkod_dot_v1_dot_agent__pb2.RecordReviewRequest.FromString,
                    response_serializer=dkod_dot_v1_dot_agent__pb2.RecordReviewResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dkod.v1.AgentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dkod.v1.AgentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AgentService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Connect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dkod.v1.AgentService/Connect',
            dkod_dot_v1_dot_agent__pb2.ConnectRequest.SerializeToString,
            dkod_dot_v1_dot_agent__pb2.ConnectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Context(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dkod.v1.AgentService/Context',
            dkod_dot_v1_dot_agent__pb2.ContextRequest.SerializeToString,
            dkod_dot_v1_dot_agent__pb2.ContextResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Submit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dkod.v1.AgentService/Submit',
            dkod_dot_v1_dot_agent__pb2.SubmitRequest.SerializeToString,
            dkod_dot_v1_dot_agent__pb2.SubmitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Verify(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/dkod.v1.AgentService/Verify',
            dkod_dot_v1_dot_agent__pb2.VerifyRequest.SerializeToString,
            dkod_dot_v1_dot_agent__pb2.VerifyStepResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Merge(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dkod.v1.AgentService/Merge',
            dkod_dot_v1_dot_agent__pb2.MergeRequest.SerializeToString,
            dkod_dot_v1_dot_agent__pb2.MergeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Watch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/dkod.v1.AgentService/Watch',
            dkod_dot_v1_dot_agent__pb2.WatchRequest.SerializeToString,
            dkod_dot_v1_dot_agent__pb2.WatchEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FileRead(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dkod.v1.AgentService/FileRead',
            dkod_dot_v1_dot_agent__pb2.FileReadRequest.SerializeToString,
            dkod_dot_v1_dot_agent__pb2.FileReadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FileWrite(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dkod.v1.AgentService/FileWrite',
            dkod_dot_v1_dot_agent__pb2.FileWriteRequest.SerializeToString,
            dkod_dot_v1_dot_agent__pb2.FileWriteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FileList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dkod.v1.AgentService/FileList',
            dkod_dot_v1_dot_agent__pb2.FileListRequest.SerializeToString,
            dkod_dot_v1_dot_agent__pb2.FileListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PreSubmitCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dkod.v1.AgentService/PreSubmitCheck',
            dkod_dot_v1_dot_agent__pb2.PreSubmitCheckRequest.SerializeToString,
            dkod_dot_v1_dot_agent__pb2.PreSubmitCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSessionStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dkod.v1.AgentService/GetSessionStatus',
            dkod_dot_v1_dot_agent__pb2.SessionStatusRequest.SerializeToString,
            dkod_dot_v1_dot_agent__pb2.SessionStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Push(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dkod.v1.AgentService/Push',
            dkod_dot_v1_dot_agent__pb2.PushRequest.SerializeToString,
            dkod_dot_v1_dot_agent__pb2.PushResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Approve(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dkod.v1.AgentService/Approve',
            dkod_dot_v1_dot_agent__pb2.ApproveRequest.SerializeToString,
            dkod_dot_v1_dot_agent__pb2.ApproveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Resolve(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dkod.v1.AgentService/Resolve',
            dkod_dot_v1_dot_agent__pb2.ResolveRequest.SerializeToString,
            dkod_dot_v1_dot_agent__pb2.ResolveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Close(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dkod.v1.AgentService/Close',
            dkod_dot_v1_dot_agent__pb2.CloseRequest.SerializeToString,
            dkod_dot_v1_dot_agent__pb2.CloseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Review(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dkod.v1.AgentService/Review',
            dkod_dot_v1_dot_agent__pb2.ReviewRequest.SerializeToString,
            dkod_dot_v1_dot_agent__pb2.ReviewResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecordReview(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dkod.v1.AgentService/RecordReview',
            dkod_dot_v1_dot_agent__pb2.RecordReviewRequest.SerializeToString,
            dkod_dot_v1_dot_agent__pb2.RecordReviewResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
